### ISSUE TITLE
Morning Stand Up Meeting Oct 24

### ISSUE THREAD

**Issue by Rhelli** [mekinus/firstHTMLProject#9]

**Comment by tcc7130** [comment]
Good things:

- Suggested videos have text on the right side

Bad things:

- In my opinion, the suggested videos should be links not videos
- ReadMe file basic sections: About the project, Built with, License, Contact, Acknoledgements

**Comment by Fig77** [comment]
Overall I think your project is looking good, just keep in mind that is better not to use inline styles on your html.
Also, here is a read me template you can use https://github.com/othneildrew/Best-README-Template/blob/master/README.md
